### ISSUE TITLE
3.1a Error in file.c while building a static tmux

### ISSUE THREAD

**Issue by mjakob-gh** [tmux/tmux#2193]
### Issue description

Using this script (https://github.com/mjakob-gh/build-static-tmux) to build a static tmux, the build stopps with this error:

> ...
> /tmp/tmux-static/bin/musl-gcc -static -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"3.1a\" -DPACKAGE_STRING=\"tmux\ 3.1a\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"3.1a\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_EXPLICIT_BZERO=1 -DHAVE_FGETLN=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_NCURSES_H=1 -DHAVE_LIBXNET=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DHAVE_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1 -I.  -DTMUX_VERSION="\"3.1a\"" -DTMUX_CONF="\"/etc/tmux.conf:~/.tmux.conf:~/.config/tmux/tmux.conf\""  -iquote.     -I/tmp/tmux-static/include -I/tmp/tmux-static/include/ncurses -I/tmp/tmux-static/include/ncurses  -std=gnu99 -O2   -I/tmp/tmux-static/include -MT file.o -MD -MP -MF $depbase.Tpo -c -o file.o file.c &&\
> mv -f $depbase.Tpo $depbase.Po
> file.c:20:23: fatal error: sys/queue.h: No such file or directory

(more lines of this log: https://travis-ci.org/github/mjakob-gh/build-static-tmux)

### Required information

Please provide the following information:

Build with these versions
- tmux 3.1a
- musl 1.2.0
- ncurses 6.1
- libevent 2.1.11

Compiler versions
- gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
- gcc version 7.4.0 (SUSE Linux)

on my test linux systems (ubuntu 20.04, Suse Leap 15.1) some queue.h files are installed in different directories, but the configure script seems not detect them. It also does not use the file compat/queue.h delivered with tmux.
Ubuntu:
- 19539 Apr 14 21:26 /usr/include/x86_64-linux-gnu/sys/queue.h
- 5542 Apr  9 12:38 /usr/include/c++/9/parallel/queue.h

Suse:
-  5542 Apr 27  2019 /usr/include/c++/7/parallel/queue.h
- 19539 May  4  2019 /usr/include/sys/queue.h

with this hack added to the script the build succeds and results in a working binary:
`sed -i 's|#include <sys/queue.h>|#include "compat/queue.h"|g' file.c` 

The build script works with the tmux releases 2.6 to 3.0, since version 3.1 this error occurs.

Anything i have to modify or add?

**Comment by nicm** [comment]
You can just remove the `#include <sys/queue.h>` line, it is not needed in portable tmux.

I will make this change for 3.1b.

I don't think the problem is that this is a static build but more that you are using a different libc.

It is unfortunate nobody tried this with any of the release candidates, because if I wouldn't doing 3.1b anyway I wouldn't do it just for this... maybe it is possible to add a build for musl to the tmux automated builds, I'll have to take a look.

**Comment by nicm** [comment]
I have added static and musl builds to tmux own GH travis, the fix to remove the #include will be in 3.1b next week. Thanks!
