### PR TITLE
Bugfix: w maybe notdefined without ENABLE_SIXEL

### PR DESCRIPTION
**Pull request by jsvisa**
This issue is introduced in 605bf21ff225c68d21577a94d423e9ec16158cdb

fix the issue of the below build error: 

```bash
make
...
input.c:2296:2: error: use of undeclared identifier 'w'
        w = wp->window;
        ^
1 warning and 1 error generated.
make: *** [input.o] Error 1
```

### CODE REVIEW

**Comment by nicm** [comment]
Fixed now, thanks!
