### ISSUE TITLE
tmux 2.7 won't compile with ncurses6.0, libevent-2.1.8

### ISSUE THREAD

**Issue by galactica147** [tmux/tmux#1338]
Hi, I'm trying to compile tmux 2.7 following instructions here: https://gist.github.com/alexnj/9371792

so i've compiled and installed ncurses-6.0, libevent-2.1.8 to some local directory (without sudo), then configured it as:

`./configure CFLAGS="-I/local_path/include -I/local_path//include/ncurses" LDFLAGS="-L/local_path/lib -L/local_path/include/ncurses -L/local_path/include".`

then compile as:
`CPPFLAGS="-I/local_path/include -I/local_path/include/ncurses" LDFLAGS="-static -L/local_path/include -L/local_path/include/ncurses -L/local_path/lib" make`

```
depbase=`echo alerts.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -std=gnu99 -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.7\" -DPACKAGE_STRING=\"tmux\ 2.7\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.7\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_NCURSES_H=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1 -I.  -DTMUX_CONF="\"/etc/tmux.conf\""  -iquote.      -std=gnu99 -O2   -I/local_path/include -I/local_path/include/ncurses -MT alerts.o -MD -MP -MF $depbase.Tpo -c -o alerts.o alerts.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from tmux.h:38:0,
                 from alerts.c:24:
compat.h:301:9: error: conflicting types for ‘forkpty’
 pid_t   forkpty(int *, char *, struct termios *, struct winsize *);
         ^
In file included from compat.h:109:0,
                 from tmux.h:38,
                 from alerts.c:24:
/usr/include/pty.h:39:12: note: previous declaration of ‘forkpty’ was here
 extern int forkpty (int *__amaster, char *__name,
            ^
make: *** [alerts.o] Error 1
```

Note that I was trying to compile using ncurses6.0 instead of 5.9, the latter of which seems to be the default version when trying to install via 'pip' or 'conda'. But some other libs would need ncurses6.0+ to run. 

Anyone knows what went wrong here? Please help fix this, many thanks!

**Comment by nicm** [comment]
Show config.log please.

**Comment by galactica147** [comment]
[config_new.log](https://github.com/tmux/tmux/files/1976968/config_new.log)
Please see the config.log here

**Comment by nicm** [comment]
It looks like you have libncurses but not libtinfo, so all the configure tests are failing:
~~~~
configure:6825: gcc -std=gnu99 -o conftest -I/local_path//include -I/local_path//include/ncurses  -L/local_path//lib -L/local_path//include/ncurses -L/local_path//include conftest.c -lutil  -levent  -lncurses >&5
/usr/bin/ld: warning: libtinfo.so.6, needed by /local_path//lib/libncurses.so, not found (try using -rpath or -rpath-link)
/local_home/.work//ccKawszm.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `fdforkpty'
/local_path//lib/libncurses.so: undefined reference to `noraw_sp'
...

**Comment by dirtyharrycallahan** [comment]
You need to look at the ncurses configure options to build libtinfo.

**Comment by galactica147** [comment]
Many thanks @nicm @dirtyharrycallahan! 
I finally managed to compile and install tmux2.7 using the correct ncurses configs, i.g., 

for compiling ncurses6.0: 
`./configure --prefix=/local_path/ --with-shared `

then for tmux we can use the above mentioned flags and link options to compile. 
Whola!

**Comment by thinkycx** [comment]
Hello! I have melt the same problem.

When I use aarch64-linux-gnu-gcc to compile it, it says
```
checking which aarch64-linux-gnu-gcc option to use... -fPIC
configure: error: Shared libraries are not supported in this version
```

compile command:
```
./configure --prefix=/root/Pwn/tmp/gdb-aarch64/tmux/tmux/ncurses-6.0/out --host=aarch64 CC=aarch64-linux-gnu-gcc --with-shared --with-build-cc=/root/Pwn/tmp/gdb-aarch64/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
```

Should I change the aarch64-linux-gnu-gcc version?
