### PR TITLE
Fix musl compile error in proc.c

### PR DESCRIPTION
**Pull request by siho22**
```
proc.c:20:10: fatal error: sys/queue.h: No such file or directory
   20 | #include <sys/queue.h>
```

This was already fixed in 7b085136, but got reintroduced with ce5de765.

### CODE REVIEW

**Comment by nicm** [comment]
Applied, thanks!
